# Generated by Django 4.2.11 on 2024-04-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visualize.industry'),
        ),
    ]
