# Generated by Django 4.2.11 on 2024-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualize', '0002_alter_organization_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(max_length=255),
        ),
    ]
